BELOW LANGUAGE MODEL osd??
sudo wget -P /usr/local/share/tessdata/ https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata
sudo wget -P /usr/local/share/tessdata/ https://github.com/tesseract-ocr/tessdata/raw/main/osd.traineddata





/1 0:00:00
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/1 -:--:--[tesseract] Error opening data file /usr/local/share/tessdata/osd.traineddata
[tesseract] Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
[tesseract] Failed loading language 'osd'
[tesseract] Tesseract couldn't load any languages!
[tesseract] Could not initialize tesseract.
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/1 -:--:--
E
======================================================================
ERROR: test_run_this_function (w_pdf.ocr_development.test_ocr.MyOCRCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ocrmypdf/_exec/tesseract.py", line 187, in get_orientation
    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ocrmypdf/subprocess/__init__.py", line 63, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tesseract', '-l', 'osd', '--psm', '0', '/tmp/ocrmypdf.io.sq4s_4u2/000001_rasterize_preview.jpg', 'stdout']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/wt/w_test/../w_pdf/ocr_development/test_ocr.py", line 32, in test_run_this_function
    is_good=call_test_run_with_test_files()
  File "/home/ubuntu/wt/w_test/../w_pdf/ocr_development/test_ocr.py", line 106, in call_test_run_with_test_files
    meta=local_run_ocr(test_file,output_filename)
  File "/home/ubuntu/wt/w_test/../w_pdf/ocr_development/test_ocr.py", line 72, in local_run_ocr
    meta=interface_pdfocr(input_filename,output_filename)
  File "/home/ubuntu/wt/w_pdf/ocr_model.py", line 58, in interface_pdfocr
    ocrmypdf.ocr(input_pdf, output_pdf, language=language,rotate_pages=True, deskew=True, force_ocr=True, jobs=jobs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ocrmypdf/api.py", line 359, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 409, in run_pipeline
    optimize_messages = exec_concurrent(context, executor)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 286, in exec_concurrent
    executor(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ocrmypdf/_concurrent.py", line 86, in __call__
    self._execute(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 138, in _execute
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 196, in exec_page_sync
    orientation_correction = get_orientation_correction(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 419, in get_orientation_correction
    orient_conf = page_context.plugin_manager.hook.get_ocr_engine().get_orientation(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 231, in get_orientation
    return tesseract.get_orientation(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ocrmypdf/_exec/tesseract.py", line 198, in get_orientation
    raise SubprocessOutputError() from e
ocrmypdf.exceptions.SubprocessOutputError

----------------------------------------------------------------------
Ran 1 test in 1.082s

FAILED (errors=1)
ubuntu@ip-172-31-21-42:~/wt$ tesseract
Usage:
  tesseract --help | --help-extra | --version
  tesseract --list-langs
  tesseract imagename outputbase [options...] [configfile...]

OCR options:
  -l LANG[+LANG]        Specify language(s) used for OCR.
NOTE: These options must occur before any configfile.

Single options:
  --help                Show this help message.
  --help-extra          Show extra help for advanced users.

